name: Node.js CI - testing

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TWILIO_ACCOUNT_SID: 123456789
      TWILIO_API_KEY_SID: 123456789
      TWILIO_API_KEY_SECRET: abcdefg
      DB_USERNAME: fake
      DB_PASSWORD: alsofake
      DB_HOST: morefake
      DB_NAME: something
      PROEVENTO_SECRET: ${{ secrets.PROEVENTO_SECRET }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      working-directory: ./api
    - run: yarn test
      working-directory: ./api
